version: 2.1
parameters:
  nombre:
    type: string
    default: Luigi
jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola << pipeline.parameters.nombre >>
workflows:
  workflow1:
    jobs:
      - saluda