version: 2.1
jobs:
  saluda:
    parameters:
      nombre:
        type: string
        default: Luigi
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola << parameters.nombre >>
workflows:
  workflow1:
    jobs:
      - saluda:
          name: saluda_Luigi
  workflow2:
    jobs:
      - saluda:
          name: saluda_Maria
          nombre: Maria