version: 2.1
commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli
      - checkout
      - run: ls -lsa
jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli
workflows:
  workflow1:
    jobs:
      - install-dependencies
---
version: 2.1
commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli
      - run: ls -lsa
jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli
      - checkout
workflows:
  workflow1:
    jobs:
      - install-dependencies
---
version: 2.1
commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli
jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli
      - checkout
      - run: find
workflows:
  workflow1:
    jobs:
      - install-dependencies
---
version: 2.1
commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli
jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli
# No admite una clave nombre pero sí admite lo que es path
      - checkout:
          path: micodigo/
      - run: find
workflows:
  workflow1:
    jobs:
      - install-dependencies