version: 2.1
jobs:
  saluda:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo hola $NOMBRE
      - run: echo mi id de job es $CIRCLE_WORKFLOW_JOB_ID
workflows:
  workflow1:
    jobs:
      - saluda
---
version: 2.1
jobs:
  saluda:
    docker:
      - image: ubuntu:latest
    steps:
      - run: 
          command: echo hola $NOMBRE
          environment:
            NOMBRE: Luigi
      - run: ls
      - run:
          command: ls
          name: nombre de mi comando
      - run:
          command: echo mi id de job es $CIRCLE_WORKFLOW_JOB_ID
workflows:
  workflow1:
    jobs:
      - saluda
---
version: 2.1
jobs:
  saluda:
    docker:
      - image: ubuntu:latest
    steps:
      - run: echo hola $NOMBRE
workflows:
  workflow1:
    jobs:
      - saluda