version: 2.1
commands:
  install-aws-cli:
    steps:
      - run: echoa instalando aws cli
jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli
# No admite una clave nombre pero sí admite lo que es path
      - checkout:
          path: micodigo/
      - run: find
workflows:
  workflow1:
    jobs:
      - install-dependencies