version: 2.1
jobs:
  saluda:
    parameters:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios
workflows:
  workflows1:
    jobs:
      - saluda
      - despidete
  workflows2:
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
  workflows3:
    jobs:
      - saluda
      - approval:
          type: approval
          requires:
            - saluda
      - despidete:
          requires:
            - approval
  every-10-minutes:
    triggers:
      - schedule:
            cron: "*/10 * * * *"
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
